### PR TITLE
Add components' information message to WNT messages

### PR DESCRIPTION
**Pull request by teemupiiroinenwirepas**
Signed-off-by: Teemu Piiroinen <teemu.piiroinen@wirepas.com>

### CODE REVIEW

**Comment by PFigs** [comment]
Please address the hound comments

**Comment by teemupiiroinenwirepas** [comment]
> 
> 
> Please address the hound comments
If I remove that line from __init__.py will the file be part of the packet? If yes, then all the import lines should be removed from that file.

**Comment by PFigs** [comment]
The import at the __init__ controls the interface for the module. If you change the filename you won't break the interface, thus makes it more resilient for the future.

In other words, with the empty __init__ you would have to do

```
from wirepas_messaging.wnt.ws_api.areamessages import AreaMessages  

or 

wirepas_messaging.wnt.ws_api.areamessages.AreaMessages()

```

If the interface is exported at the wnt level (as currently is), then you can do

```
from wirepas_messaging.wnt import AreaMessages 

or call it with

wirepas_messaging.wnt.AreaMessages()
```

I prefer the second. I could compromise on changing the import at wnt/__init__.py from

` from .ws_api import *`

to

`from . import ws_api `

What do you think?

**Comment by teemupiiroinenwirepas** [comment]
I'll create separate pull request for that "from . import ws_api"

**Pull request merged**
